import { RoleType } from "@/types";

export const Roles: RoleType[] = [
  {
    id: "frontend",
    name: "frontend",
    inConstruction: false,
    estimatedTime: "3-6 months",
    difficulty: "Intermediate",
    topics: "10+",
  },
  {
    id: "backend",
    name: "backend",
    inConstruction: false,
    estimatedTime: "4-8 months",
    difficulty: "Intermediate",
    topics: "14+",
  },
  {
    id: "fullstack",
    name: "fullstack",
    inConstruction: false,
    estimatedTime: "6-12 months",
    difficulty: "Advanced",
    topics: "20+",
  },
  {
    id: "devops",
    name: "devops",
    inConstruction: false,
    estimatedTime: "4-8 months",
    difficulty: "Advanced",
    topics: "12+",
  },
  {
    id: "app_dev",
    name: "app development",
    inConstruction: false,
    estimatedTime: "3-6 months",
    difficulty: "Intermediate",
    topics: "8+",
  },
  {
    id: "data_science",
    name: "data science",
    inConstruction: true,
    estimatedTime: "6-12 months",
    difficulty: "Advanced",
    topics: "15+",
  },
  {
    id: "ai_engineer",
    name: "ai engineer",
    inConstruction: true,
    estimatedTime: "12-18 months",
    difficulty: "Expert",
    topics: "18+",
  },
];

export const Lang: RoleType[] = [
  {
    id: "HTML",
    name: "HTML",
    inConstruction: true,
    estimatedTime: "1-2 weeks",
    difficulty: "Intermediate",
    topics: "5+",
  },
  {
    id: "CSS",
    name: "CSS",
    inConstruction: true,
    estimatedTime: "2-4 weeks",
    difficulty: "Intermediate",
    topics: "7+",
  },
  {
    id: "javascript",
    name: "javascript",
    inConstruction: true,
    estimatedTime: "2-3 months",
    difficulty: "Intermediate",
    topics: "12+",
  },
  {
    id: "typescript",
    name: "typescript",
    inConstruction: true,
    estimatedTime: "1-2 months",
    difficulty: "Intermediate",
    topics: "8+",
  },
  {
    id: "tailwindcss",
    name: "tailwindcss",
    inConstruction: true,
    estimatedTime: "2-4 weeks",
    difficulty: "Intermediate",
    topics: "6+",
  },
  {
    id: "sql",
    name: "sql",
    inConstruction: true,
    estimatedTime: "1-2 months",
    difficulty: "Intermediate",
    topics: "10+",
  },
  {
    id: "postgressql",
    name: "postgressql",
    inConstruction: true,
    estimatedTime: "1-2 months",
    difficulty: "Intermediate",
    topics: "9+",
  },
  {
    id: "mongodb",
    name: "mongodb",
    inConstruction: true,
    estimatedTime: "1-2 months",
    difficulty: "Intermediate",
    topics: "8+",
  },
  {
    id: "prismadb",
    name: "prismadb",
    inConstruction: true,
    estimatedTime: "1-2 months",
    difficulty: "Intermediate",
    topics: "7+",
  },
  {
    id: "next js",
    name: "next js",
    inConstruction: true,
    estimatedTime: "2-4 months",
    difficulty: "Advanced",
    topics: "15+",
  },
  {
    id: "react js",
    name: "react js",
    inConstruction: true,
    estimatedTime: "2-4 months",
    difficulty: "Advanced",
    topics: "15+",
  },
];

export const projects = [
  {
    id: 1,
    name: "frontend",
    topics: "3+",
  },
  {
    id: 2,
    name: "backend",
    topics: "4+",
  },
  {
    id: 3,
    name: "fullstack",
    topics: "5+",
  },
];
